// MS-react-ES6/app/components/MusicNav/MusicNav.jsx
import React from 'react'
import CSSModules from 'react-css-modules'
import styles from "./MusicNav.css"
const MusicNav = (props) => {
  	let title = null
  	if(props.showName)
  		title = (
  			<div className="name">
		        <span>{props.username}</span>，欢迎回来！
		    </div>
  		)
  	else
  		title = (
  			<span className="navbar-brand">音乐分享平台</span>
  		)

	return (
		<nav className="navbar navbar-inverse navbar-fixed-top">
		    <div className="navbar-header">
		        <button type="button" className="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
		            <span className="sr-only">Toggle navigation</span>
		            <span className="icon-bar"></span>
		            <span className="icon-bar"></span>
		            <span className="icon-bar"></span>
		        </button>
		        {title}
		    </div>
		    <div className="collapse navbar-collapse" id="navbar">
		        <ul className="nav navbar-nav">
		            {props.children}
		        </ul>
		    </div>
		</nav>
	)
}

export default CSSModules(MusicNav, styles)

// MS-others/apps/MS-vuex-ES6/components/musicNav/index.vue
<template>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <span v-if="!showName" class="navbar-brand">音乐分享平台</span>
        <div v-if="showName" class="name">
            <span>{{username}}</span>，欢迎回来！
        </div>
    </div>
    <div class="collapse navbar-collapse" id="navbar">
        <ul class="nav navbar-nav">
            <slot></slot>
        </ul>
    </div>
</nav>
</template>
<style scoped>
.name{
    color:white;
    font-size: 20px;
    line-height: 50px; 
    height: 50px; 
    padding:0 5%;
}
.name span{
    color:red!important;
}
.navbar-nav {
    color:white;
}
@media (max-width: 767px){
    .navbar-nav > li {
        font-size: 20px;
        line-height: 50px;
        height: 50px;
        margin:0 5%;
    }   
}

@media (min-width: 768px) {
    .navbar-nav{
        float: right;
    }
    .navbar-header{
        min-width: 200px;
    }
    .navbar-nav > li {
        cursor : pointer;
        margin-right: 20px; 
        padding-top: 15px;
        padding-bottom: 15px;
    }
}
</style>
<script>
export default {
    name : 'musicNav',
    props : {
        showName : { 
            type : Boolean
        }, 
        username : {
            type : String, 
            default : ""
        }
    }
}
</script>
