// MS-react-ES6/app/views/checkShareRequest.jsx
import React from 'react'
import {withRouter} from "react-router-dom"

import MusicNav from "../components/MusicNav/MusicNav.jsx"
import MusicModal from "../components/MusicModal/MusicModal.jsx"

import styles from '../css/checkShareRequest.css'
class CheckShareRequest extends React.Component {
   	render() {
   		let checkShareList = this.state.shareRequests.map((shareRequest, index)=>(
			<li key={index} className="list-group-item">
	            <p>歌曲名称：<span className='fr'>{shareRequest.song.name}</span></p>
	            <p>发起人：<span className='fr'>{shareRequest.owner.name}</span></p>
	            <p>接收人：<span className='fr'>{shareRequest.target.name}</span></p>
	            <p>类型：
	            	{shareRequest.owner.name==this.state.user.name &&
	                	<span className='fr'>发起</span>
	            	}
	            	{shareRequest.target.name==this.state.user.name &&
	                	<span className='fr'>接收</span>
	            	}
	            </p>
	            {shareRequest.target.name==this.state.user.name && shareRequest.status==0 &&
		            <div className="row">
		                <button className="btn btn-success col-xs-3 col-xs-offset-2"
		                	onClick={this.replyShareRequest.bind(this, shareRequest._id, 1)}>
		                	同意请求
		                </button>
		                <button className="btn btn-danger col-xs-3 col-xs-offset-2"
		                	onClick={this.replyShareRequest.bind(this, shareRequest._id, 2)}>
		                	拒绝请求
		                </button>
		            </div>
	            }
	            {shareRequest.status==1 &&
	            	<p className="text-center text-success">已成功操作</p>
	            }
	            {shareRequest.status==2 &&
	            	<p className="text-center text-danger">已拒绝操作</p>
	            }
	        </li>
   		))

   		let friendList = this.state.user.friends.map((friend, index)=>(
            <tr key={index}>
                <th>{friend.name}</th>
                <th>
                    <button type="button" className="btn btn-primary"
                    	onClick={this.selectFriend.bind(this, friend)}>  
                        选择
                    </button>
                </th>
            </tr>
   		))


   		let songList = this.state.user.songs.map((song, index)=>(
		    <tr key={index}>
	            <th>{song.name}</th>
	            <th>
	                <button type="button" className="btn btn-primary"
	                	onClick={this.selectSong.bind(this, song)} data-dismiss="modal"> 
	                    选择并确定
	                </button>
	            </th>
	        </tr>
   		))

     	return (
			<div className="container checkShareRequest">
			    <MusicNav showName={true} username={this.state.user.name}>
			        <li onClick={this.toLogin.bind(this)}>注销</li>
			        <li onClick={this.toHome.bind(this)}>个人中心</li>  
			    </MusicNav>
			    <ul className="nav nav-pills" role="tablist">
			        <li role="presentation" className="active">
			            <a href="javascript:;">分享事项</a>
			        </li>
			        <button className='btn btn-success pull-right'
			        	data-toggle="modal" data-target="#myModal">
			        	点击创建分享
			        </button>
			    </ul>
			    <div className="checkShareList">
			    	{this.state.shareRequests.length == 0 &&
			        	<span className="text-danger">无</span>
			    	}
			    	{this.state.shareRequests.length != 0 &&
			        	<ul className="list-group">
			            	{checkShareList}
			        	</ul>       
			    	}
			    </div>
			    <MusicModal id="myModal">
		    		<div key="title">
		            	<button type="button" className="close" data-dismiss="modal" aria-label="Close" onClick={this.resetStatus.bind(this)}>
		                	<span aria-hidden="true">&times;</span>
		            	</button>
		            	{this.state.shareOperationStatus==0 &&
		            		<h4 className="modal-title" id="myModalLabel">选择好友</h4>
		            	}
		            	{this.state.shareOperationStatus==1 &&
		            		<h4 className="modal-title" id="myModalLabel">选择歌曲</h4>
		            	}
		        	</div>	
			        <div key="body">
			        	{this.state.shareOperationStatus==0 &&
				            <table className="table">
				                <thead>
				                    <tr>
				                        <th>姓名</th>
				                        <th>操作</th>
				                    </tr>
				                </thead>
				                <tbody>
				                	{friendList}
				                </tbody>
				            </table>
			        	}
			        	{this.state.shareOperationStatus==1 &&
				            <table className="table">
				                <thead>
				                    <tr>
				                        <th>歌曲名</th>
				                        <th>操作</th>
				                    </tr>
				                </thead>
				                <tbody>
				                	{songList}
				                </tbody>
				            </table>
			        	}
			        </div>
			    	<div key="footer">
			            <button type="button" className="btn btn-default"
			            	data-dismiss="modal" onClick={this.resetStatus.bind(this)}>
			            	关闭
			            </button>
			    	</div>
			    </MusicModal>

			</div> 
    	)
    }
        constructor(props) {
    	super(props)
    	this.state = {
            user : {
            	songs : [], 
            	friends : []
            }, 
            shareRequests : [], 
            shareOperationStatus : 0, 
            friendName : ""
    	}
  	}
  	componentDidMount(){
        let id = localStorage.getItem("identity")
        if (id == null)
            this.props.history.push("/login") 
        this.setState({id:id})

        var _this = this
        $.get('checkshareRequest?id=' + id, 
        	(data)=>{
                if(data.result==='success'){
                	_this.setState({
                		user : data.data.user, 
                		shareRequests : data.data.shareRequests
                	})
                } else {
                    alert(data.message)
                }
        	}
        ) 
  	}
	selectFriend(friend){
        this.setState({
        	shareOperationStatus : 1, 
        	friendName : friend.name
        })
    }
    selectSong(song){
        this.setState({shareOperationStatus : 0})
        if(this.state.friendName == ""){
            alert("未知错误！"); 
            return; 
        }
        var _this = this
        let postData = {
            id : _this.state.id, 
            friendName : _this.state.friendName, 
            songId : song._id
        } 
        $.post('addShare', postData, 
        	(data)=>{
                if(data.result==='success'){
                    alert("分享已经发送！")
                    window.location.reload()
                } else {
                    alert(data.message)
                }
        	}
        )
    }
    resetStatus(){
        this.setState({shareOperationStatus : 0})
    }
    replyShareRequest(requestId, status){
        let postData = {
           requestId : requestId,
           status : status
        }  
        $.post('replyShareRequest', postData, 
        	(data)=>{
                if(data.result==='success'){
                    alert("您的回复已经发送！歌曲会出现在您列表里！")
                    window.location.reload()
                } else {
                    alert(data.message)
                }
        	}
        )   
    }
    toLogin(){
        localStorage.removeItem("identity")
    	this.props.history.push("/login")  
    } 
    toHome(){
    	this.props.history.push("/home")  
    }
}
export default withRouter(CheckShareRequest)

// MS-vue-ES6/app/views/checkShareRequest.vue
<template>
<div class="container checkShareRequest">
    <music-nav v-bind:showName="true" v-bind:username="user.name">
        <li @click="toLogin()">注销</li>
        <li @click="toHome()">个人中心</li>  
    </music-nav>
    <ul class="nav nav-pills" role="tablist">
        <li role="presentation" class="active">
            <a href="javascript:;">分享事项</a>
        </li>
        <button class='btn btn-success pull-right' data-toggle="modal" data-target="#myModal">点击创建分享</button>
    </ul>
    <div class="checkShareList">
        <span v-if="shareRequests.length==0" class="text-danger">无</span>
        <ul v-if="shareRequests.length!=0" class="list-group">

            <li class="list-group-item" v-for="shareRequest in shareRequests">
                <p>歌曲名称：<span class='fr'>{{shareRequest.song.name}}</span></p>
                <p>发起人：<span class='fr'>{{shareRequest.owner.name}}</span></p>
                <p>接收人：<span class='fr'>{{shareRequest.target.name}}</span></p>
                <p>类型：
                    <span class='fr' v-if="shareRequest.owner.name==user.name">发起</span>
                    <span class='fr' v-if="shareRequest.target.name==user.name">接收</span>
                </p>
                <div class="row" v-if="shareRequest.target.name==user.name&&shareRequest.status==0">
                    <button class="btn btn-success col-xs-3 col-xs-offset-2" @click="replyShareRequest(shareRequest._id, 1)">同意请求</button>
                    <button class="btn btn-danger col-xs-3 col-xs-offset-2" @click="replyShareRequest(shareRequest._id, 2)">拒绝请求</button>
                </div>
                <p class="text-center text-success" v-if="shareRequest.status==1">已成功操作</p>
                <p class="text-center text-danger" v-if="shareRequest.status==2">已拒绝操作</p>
            </li>
        </ul>       
    </div>
    <!-- Modal -->
    <music-modal id="myModal">
        <div slot="title">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close" @click="resetStatus()">
                <span aria-hidden="true">&times;</span>
            </button>
            <h4 class="modal-title" id="myModalLabel" v-if="shareOperationStatus==0">选择好友</h4>
            <h4 class="modal-title" id="myModalLabel" v-if="shareOperationStatus==1">选择歌曲</h4>
        </div>
        <div slot="body">
            <table class="table" v-if="shareOperationStatus==0">
                <thead>
                    <tr>
                        <th>姓名</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="friend in user.friends">
                        <th>{{friend.name}}</th>
                        <th>
                            <button type="button" class="btn btn-primary" @click.stop="selectFriend(friend)">  
                                选择
                            </button>
                        </th>
                    </tr>
                </tbody>
            </table>
            <table class="table" v-if="shareOperationStatus==1">
                <thead>
                    <tr>
                        <th>歌曲名</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="song in user.songs">
                        <th>{{song.name}}</th>
                        <th>
                            <button type="button" class="btn btn-primary" @click="selectSong(song)" data-dismiss="modal"> 
                                选择并确定
                            </button>
                        </th>
                    </tr>
                </tbody>
            </table>
        </div>
        <div slot="footer">
            <button type="button" class="btn btn-default" data-dismiss="modal" @click="resetStatus()">关闭</button>
        </div>
    </music-modal>
</div>  
</template>
<script>
import musicNav from '../components/musicNav'
import musicModal from '../components/musicModal'
export default {
    components : {
        musicNav, 
        musicModal
    },
    data () {
        return {
            user : {}, 
            shareRequests : [], 
            shareOperationStatus : 0, 
            friendName : ""

        }
    },
    created() {
        this.id = localStorage.getItem("identity")
        if (this.id == null)
            this.$router.push({name:'login'})   

        this.$http.get('checkshareRequest?id=' + this.id)
            .then(function (response) {
                if(response.data.result==='success'){
                    this.user = response.data.data.user
                    this.shareRequests = response.data.data.shareRequests
                } else {
                    alert(response.data.message)
                }
            }, function (err) {

            })  
    }, 
    methods:{
        selectFriend(friend){
            this.shareOperationStatus = 1
            this.friendName = friend.name
        },
        selectSong(song){
            this.shareOperationStatus = 0;
            if(this.friendName == ""){
                alert("未知错误！"); 
                return; 
            }
            let postData = {
                id : this.id, 
                friendName : this.friendName, 
                songId : song._id
            } 
            this.$http.post('addShare', postData)
                .then(function (response) {
                    if(response.data.result==='success'){
                        alert("分享已经发送！")
                        window.location.reload()
                    } else {
                        alert(response.data.message)
                    }
                }, function (err) {

                }) 
        },
        resetStatus(){
            this.shareOperationStatus = 0
        },
        replyShareRequest(requestId, status){
            let postData = {
               requestId : requestId,
               status : status
            }  
            this.$http.post('replyShareRequest', postData)
                .then(function (response) {
                    if(response.data.result==='success'){
                        alert("您的回复已经发送！歌曲会出现在您列表里！")
                        window.location.reload()
                    } else {
                        alert(response.data.message)
                    }
                }, function (err) {

                })     
        },
        toLogin(){
            localStorage.removeItem("identity")
            this.$router.push({name:'login'})  
        }, 
        toHome(){
            this.$router.push({name:'home'})  
        }
    }
}
</script>
<style scoped>
.nav-pills{
    padding-top: 20px; 
    margin-bottom: 10px; 
}

.checkShareList .list-group-item p{
    line-height: 34px; 
    height: 34px; 
    font-size: 16px; 
}
</style>
