// MS-others/apps/MS-vuex-ES6/components/musicModal/index.vue
<template>
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <slot name="title"></slot>
            </div>
            <div class="modal-body">
                <slot name="body"></slot>
            </div>
            <div class="modal-footer">
                <slot name="footer"></slot>
            </div>
        </div>
    </div>
</div>
</template>
<style scoped>

</style>
<script>
export default {
    name : 'musicModal'
}
</script>

// MS-react-ES6/app/components/MusicModal/MusicModal.jsx
import React from 'react'
import CSSModules from 'react-css-modules'
import styles from "./MusicModal.css"

const MusicModal = (props) =>{

    var getComponent =(key)=>{
        return props.children.filter( (comp) => {
            return comp.key === key
        })
    }
    return(
        <div id={props.id} className="modal fade" tabIndex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div className="modal-dialog" role="document">
                <div className="modal-content">
                    <div className="modal-header">
                        {getComponent('title')}
                    </div>
                    <div className="modal-body">
                        {getComponent('body')}
                    </div>
                    <div className="modal-footer">
                        {getComponent('footer')}
                    </div>
                </div>
            </div>
        </div>
    )
}
export default CSSModules(MusicModal, styles)
