// MS-vue-ES6/app/views/main.vue
<template>
<div class="container">
    <music-nav v-bind:showName="false">
        <li v-if="!id">未登录</li>
        <li v-if="id">已登录</li> 
    </music-nav>
    <img src="https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=2550279230,467606093&fm=200&gp=0.jpg" class="img-responsive logo" alt="欢迎使用音乐分享平台">
    <img src="https://cn.vuejs.org/images/logo.png" class="img-responsive version_logo">
    <h1 class="version_text">VUE版本</h1>        
        
    <p>这是一个音乐分享平台，实现音乐上传，在线播放，添加好友和给好友分享音乐的功能。</p>
    <p>响应式设计同时支持移动端和电脑端，上传音乐IOS端请使用icoud drive上传</p>
    <p>项目逻辑不复杂，功能不多，本人做这个项目仅供学习，严禁任何人用于商业。</p>
    <p>希望能帮助大家学习框架API的使用，以及对不同框架的差别理解。</p>

    <div class="row" v-if="!id">
        <button class="btn btn-primary col-xs-3 col-xs-offset-2" @click="toLogin()">
            <span>点此登录</span>
        </button>
        <button class="btn btn-success col-xs-3 col-xs-offset-2" @click="toApply()">
            <span>注册</span>
        </button>
    </div>
    <div class="row" v-if="id">
        <button class="btn btn-primary col-xs-6 col-xs-offset-3" @click="toHome()" >
            <span>点此进入首页</span>
        </button>
    </div>
    <br>
    <p>作者：星空下的凡尘</p>
    <p>邮箱：645566979@qq.com</p>
</div>
</template>

<script>
import musicNav from '../components/musicNav'
export default {
    components : {
        musicNav
    },
    data () {
        return {
            id : ""
        }
    },
    created() {
        this.id = localStorage.getItem("identity")
    },
    methods:{
        toLogin(){
            this.$router.push({name:'login'})
        }, 
        toHome(){
            this.$router.push({name:'home'})
        }, 
        toApply(){
            this.$router.push({name:'apply'})

        
        }
    }
}
</script>

<style scoped>
.logo{
    width:200px;
    margin:0 auto;
}
.version_logo{
    width:60px;
    margin:0 auto;
}
.version_text{
    text-align: center;
}
</style>

// MS-react-ES6/app/views/main.jsx
import React from 'react'
import {withRouter} from "react-router-dom"
import CSSModules from 'react-css-modules'
import styles from '../css/main.css'

import MusicNav from '../components/MusicNav/MusicNav.jsx'
class Main extends React.Component {
   	render() {
   		let mainButton = null
   		if(this.state.id)
   			mainButton = (
   				<button className="btn btn-primary col-xs-6 col-xs-offset-3" onClick={this.toHome.bind(this)}>
			        <span>点此进入首页</span>
			    </button>	
   			)
   		else
   			mainButton = (
          <div className="row">
            <button className="btn btn-primary col-xs-3 col-xs-offset-2" onClick={this.toLogin.bind(this)}>
              <span>点此登录</span>
            </button>
            <button className="btn btn-success col-xs-3 col-xs-offset-2" onClick={this.toApply.bind(this)}>
              <span>注册</span>
            </button>
          </div>
   			)

   		let status = null
   		if(this.state.id)
   			status = (
   				<li>已登录</li>
   			)
   		else
   			status = (
   				<li>未登录</li>
   			)


     	return (
    			<div className="container">
    				<MusicNav showName={false}>
    	     			{status}
    	     	</MusicNav>
            <img src="https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=2550279230,467606093&fm=200&gp=0.jpg" className="img-responsive logo" alt="欢迎使用音乐分享平台"/>
            <img src="https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=1952752745,2045652368&fm=15&gp=0.jpg" className="img-responsive version_logo"/>
            <h1 className="version_text">REACT版本</h1>        
            <p>这是一个音乐分享平台，实现音乐上传，在线播放，添加好友和给好友分享音乐的功能。</p>
            <p>响应式设计同时支持移动端和电脑端，上传音乐IOS端请使用icoud drive上传</p>
            <p>项目逻辑不复杂，功能不多，本人做这个项目仅供学习，严禁任何人用于商业。</p>
            <p>希望能帮助大家学习框架API的使用，以及对不同框架的差别理解。</p>
    				{mainButton}
            <br></br>
            <p className="marginTop20">作者：星空下的凡尘</p>
            <p>邮箱：645566979@qq.com</p>
    			</div>
    	)
    }
    constructor(props) {
    	super(props)
    	this.state = {
            id : ""
    	}
  	}
  	componentDidMount(){
        this.setState({id : localStorage.getItem("identity")})
  	}
	toLogin(){
		this.props.history.push("/login")
	}
  toHome(){
    this.props.history.push("/home")
  }
  toApply(){
    this.props.history.push("/apply")
  }
}
export default CSSModules(withRouter(Main), styles)
