// MS-react-ES6/app/views/login.jsx
import React from 'react'
import {withRouter} from "react-router-dom"

import MusicNav from "../components/MusicNav/MusicNav.jsx"
import style from '../css/login.css'
class Login extends React.Component {
   	render() {
     	return (
          <div className="container login">
              <MusicNav showName={false}>
                  <li onClick={this.toMain.bind(this)}>返回首页</li>
              </MusicNav>
              <div className="panel panel-primary">
                  <div className="panel-heading">
                      <h3 className="panel-title">音乐分享平台</h3>
                  </div>
                  <div className="panel-body">
                      <div className="form-group">
                          <label>登录名</label>
                          <input type="text" className="form-control" placeholder="请输入登录名" 
                              value={this.state.username} onChange={evt => this.updateUsername(evt)}/>
                      </div>
                      <div className="form-group">
                          <label>密码</label>
                          <input type="password" className="form-control" placeholder="请输入密码"
                              value={this.state.password} onChange={evt => this.updatePassword(evt)}/>
                      </div>
                      <div className="row">
                          <button className="btn btn-primary col-xs-4 col-xs-offset-4" onClick={this.toHome.bind(this)}>登录</button>
                      </div>
                  </div>
              </div>
          </div>
    	)
    }
    constructor(props) {
    	super(props)
    	this.state = {
      		id: "", 
      		username : "",
      		password : ""
    	}
  	}

  	componentDidMount(){
    	this.state.id = localStorage.getItem("identity")
        if (this.state.id !== null){
            this.props.history.push("/home")      
        }
  	}
    toHome(){
        if (this.state.username==="") {
            alert("账号不能为空")
            return; 
        }
        else if (this.state.password==="") {
            alert("密码不能为空")
            return; 
        }
        let postData = {
            username : this.state.username, 
            password : this.state.password
        }
        var _this = this
        $.post("login", postData,
            function(data) {
    				    if(data.result==='success'){
                    localStorage.setItem("identity", data.data)
                    _this.props.history.push("/home")  
                } else {
                    alert(data.message)
                }
            }
        )
    }
    toMain(){
      this.props.history.push("/main")  
    }
    updateUsername(evt) {
    	this.setState({
      		username: evt.target.value
    	})
  	}
  	updatePassword(evt) {
    	this.setState({
      		password: evt.target.value
    	})
  	}

}
export default withRouter(Login)

// MS-others/apps/MS-vuex-ES6/views/login/index.vue
<template>
<div :style="backgroundDiv" class="container login">
    <music-nav v-bind:showName="false">
        <li @click="toMain()">返回首页</li>
    </music-nav>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">音乐分享平台</h3>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <label>登录名</label>
                <input type="text" class="form-control" placeholder="请输入登录名"
                    :value="username" @input="updateUsername">
            </div>
            <div class="form-group">
                <label>密码</label>
                <input type="password" class="form-control" placeholder="请输入密码"
                    :value="password" @input="updatePassword">
            </div>
            <div class="row">
                <button class="btn btn-primary col-xs-3 col-xs-offset-2" @click="toHome()">登录</button>
                <button class="btn btn-success col-xs-3 col-xs-offset-2" @click="toApply()">注册</button>
            </div>
        </div>
    </div>
</div>
</template>

<script>
import elephant from '../../elephant-ui'
import musicNav from '../../components/musicNav'
import store from './store'
const http = elephant.http
const bus = elephant.bus 
//模块名称及局部数据
let moduleData = {
    mName : 'login', 
    store,
}
//组件数据的配置项
let vuexSettings = {
    state : {
        self : ['username', 'password'], 
        global : ['id']
    }, 
    mutations : {
        self : ['SET_VALUE'], 
        global : ['INIT_ID']
    }, 
    actions : {
        self : ['API_LOGIN']
    }
}
//vue组件配置项
let vueComponent = {
    components : {
        musicNav
    },
    data () {
        return {
            backgroundDiv :  {
                backgroundImage: 'url(' + require('../../images/bg1.jpg') + ')',
            }
        }
    },
    created() {
        this.INIT_ID()
        if (this.id !== null){
            this.$router.push('home')      
        }

    }, 
    methods: {
        toMain(){
            this.$router.push({name:'main'})
        },
        toApply(){
            this.$router.push({name:'apply'})
        },
        toHome(){
            this.API_LOGIN().then(()=>{
                this.$router.push({name:'home'})
            })
        }, 
        updateUsername(e){
            this.SET_VALUE({username: e.target.value})
        },
        updatePassword(e){
            this.SET_VALUE({password: e.target.value})
        }, 
    }
}
export default elephant.component(vueComponent, vuexSettings, moduleData)
</script>

<style scoped>
.login{
    background:no-repeat 0px 0px;
    background-size:cover;
    -webkit-background-size:cover;
    -moz-background-size:cover;
    -o-background-size:cover;
    min-height:700px;
    padding-top:20px;
    width:100%;
}
</style>
