// MS-react-ES6/app/components/MusicMessageBox/MusicMessageBox.jsx
import React from 'react'
import CSSModules from 'react-css-modules'
import styles from "./MusicMessageBox.css"
import bus from '../../bus'

class MusicMessageBox extends React.Component{
    constructor(props) {
        super(props)
        this.state = {
            messageBox : {
                type : '', 
                message : '', 
                callback : null
            }
        }
    }
    callback(){
        if(this.state.messageBox.callback)
            this.state.messageBox.callback()
    }
    componentDidMount(){
        var _this = this
        bus.subscribe('alert', (message, callback)=>{
            _this.setState({
                messageBox : {
                    type : 'alert', 
                    message : message, 
                    callback : callback
                }    
            })
            $("#messageBox").modal()
        })
        bus.subscribe('confirm', (message, callback)=>{
            _this.setState({
                messageBox : {
                    type : 'confirm', 
                    message : message, 
                    callback : callback
                }    
            })
            $("#messageBox").modal()
        })

    }
    render(){
        return(
            <div id={this.props.id} className="modal fade" tabIndex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div className="modal-dialog" role="document">
                    <div className="modal-content">
                        <div className="modal-header">
                            {this.state.messageBox.type =='alert' &&
                               <span>提示</span>
                            }
                            {this.state.messageBox.type =='confirm' &&
                                <span>请确认</span>
                            }
                        </div>
                        <div className="modal-body">
                            {this.state.messageBox.message}
                        </div>
                        <div className="modal-footer">
                            {this.state.messageBox.type =='alert' &&
                                <div className="row">
                                    <button type="button" className="btn btn-default col-xs-4 col-xs-offset-4" data-dismiss="modal" onClick={this.callback.bind(this)}>关闭</button>
                                </div>
                            }
                            {this.state.messageBox.type =='confirm' &&
                                <div className='row'>
                                    <div className="col-xs-3 col-xs-offset-2">
                                        <button type="button" className="btn btn-default" data-dismiss="modal"  onClick={this.callback.bind(this)}>确认</button>
                                    </div>
                                    <div className="col-xs-3 col-xs-offset-2">
                                        <button type="button" className="btn btn-default" data-dismiss="modal">取消</button>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        )      
    }

}
export default CSSModules(MusicMessageBox, styles)

// MS-vuex/apps/MS-vuex-ES6/components/musicMessageBox/index.vue
<template>
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <span v-if="messageBox.type=='alert'">提示</span>
                <span v-if="messageBox.type=='confirm'">请确认</span>
            </div>
            <div class="modal-body">{{messageBox.message}}</div>
            <div class="modal-footer">
                <div class="row" v-if="messageBox.type=='alert'">
                    <button type="button" class="btn btn-default col-xs-4 col-xs-offset-4" data-dismiss="modal" @click="callback()">关闭</button>
                </div>
                <div class='row' v-if="messageBox.type=='confirm'">
                    <div class="col-xs-3 col-xs-offset-2">
                        <button type="button" class="btn btn-default" data-dismiss="modal" @click="callback()">确认</button>
                    </div>
                    <div class="col-xs-3 col-xs-offset-2">
                        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</template>
<style scoped>

</style>
<script>
import bus from '@/bus'
import elephant from '@/elephant-ui'
import * as types from '../../mutation-types'
const store = {
    namespaced:true, 
    state : {
        messageBox : {
            type : '', 
            message : '', 
            callback : null
        }
    }, 
    mutations : {
        [types.SET_VALUE] (state, obj) {           //eg: commit("SET_VALUE", {user:xxx, id:xxx})
            for (var index in obj) { 
                state[index] = obj[index]
            }
        },
    },
}
//模块名称及局部数据
let moduleData = {
    mName : 'musicMessageBox', 
    store, 
}
//组件数据的配置项
let vuexSettings = {
    state : {
        self : ['messageBox']
    }, 
    mutations : {
        self : ['SET_VALUE']
    }
}
//vue组件配置项
let vueComponent = {
    name : 'musicMessageBox',
    mounted () {
        bus.$on("alert", function (message, callback) {
            this.SET_VALUE({
                messageBox : {
                    type : 'alert', 
                    message : message, 
                    callback : callback
                } 
            })
            $("#messageBox").modal()
        }.bind(this))
        bus.$on("confirm", function (message, callback) {
            this.SET_VALUE({
                messageBox : {
                    type : 'confirm', 
                    message : message, 
                    callback : callback
                } 
            })
            $("#messageBox").modal()
        }.bind(this))
    },
    methods: {
        callback(){
            if(this.messageBox.callback)
                this.messageBox.callback()
        }
    }
}
export default elephant.component(vueComponent, vuexSettings, moduleData)
</script>
